### ISSUE TITLE
FIX newly added subdomains should work immediately

### ISSUE THREAD

**Issue by allanlaal** [zpanel/zpanelx#128]
right now it seems I need to manually rerun the zPanel daemon and restart the apache2 service. Otherwise newly added subdomains just show the zPanel login page (which cannot be changed into a placeholder as far as I know).

mind you that *.exampledomain.com is already directed to the zPanel server, so its not a DNS issue.

**Comment by motters** [comment]
This sounds like an error that is just on your system as no one else has reported this issue and its quite an obvious error at that haha.

Post up on the forums for help http://forums.zpanelcp.com/

**Comment by allebb** [comment]
I'd check the syslog for any permission errors, A total stab in the dark
but I reckon you'll find that the issue is related to cron permissions :) -
Check /var/log/syslog and see what you find in there...

Like @Motters says though, the fact that no one else has reported issues
with regards to the daemon not running would indicate that the issue
is only affecting you and therefore an isolated occurrence. :(

**Comment by dansanti** [comment]
mmm.. try forcing a update from here http://you-server/?module=apache_admin  this work to me

**Comment by allanlaal** [comment]
So this is a bug afterall? I cant have my clients call me to force an 
update every time they add a subdomain

**Comment by allebb** [comment]
Its not a but with the Zpanel software, it is how your server is configured to run the cron job, check syslog - i reckon you'll need to reset linux file system perms on the cron file (zdaenon).

**Comment by allanlaal** [comment]
No errors in syslog,  bug still present.

Dirty fixed with: http://forums.zpanelcp.com/Thread-Apache-reload-not-working-in-Ubuntu-12-04?pid=53230#pid53230
https://gist.github.com/allanlaal/9491526
