### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by mro95** [zpanel/zpanelx#132]
Hi,
I really like MariaDB. Can you make support for MariaDB?

**Comment by trojanspike** [comment]
MariaDB just slots in for mySql , best for this to come from yourself or a developer addon, not zpanel core

**Comment by allebb** [comment]
Yeah @trojanspike is correct, MariaDB is a direct drop-in for MySQL therefore no special requirements are required in the code, just uninstall and install MariaDB if you wish :)

**Comment by BastianBalthasarBux** [comment]
this is not 100% correct @bobsta63 and @trojanspike. mariadb at least needs some adjustments of the installer script. ATM on e.g. centos 7 the script does NOT work, due to the dead simple fact, that "service mysqld start" does not work as mysqld.service is not present after installation of mariadb on some machines like already mentioned centos 7, and reportedly also fedora 20. this leads to some nice, confusing type-password-loop.

**Comment by 5050** [comment]
Hi, 
As you may have seen, you responded to a thread where last post was from more than 8 months ago ! From what I know, nor bobsta63 nor troyanspike are still involved in zPanel, but you may want to try [Sentora](http://sentora.org) which uses mariadb for Centos 7.

**Comment by BastianBalthasarBux** [comment]
Sorry, I didn't realy look at the date, I just stumbled upon via online search, and because the problem is still present, I decided to post, so others which may stumble upon have a more qualified answer than 'should work', which is simply wrong.
Thank you for answering me anyway. Maybe I'll give Sentora, zpanel already lost the competition, this time.
