### ISSUE TITLE
Feature request: point sub domain to ANY FOLDER not only existing root/New

### ISSUE THREAD

**Issue by vrdvaibhav** [zpanel/zpanelx#139]
I saw this post from Forum, someone already requested for this feature
http://forums.zpanelcp.com/Thread-Feature-request-point-sub-domain-to-ANY-FOLDER-not-only-existing-root-New

I also want to point sub domain to folder inside home/root folder. This feature is not yet added , for my symfony 1.4 website I just want to point to "web" folder within the root.home folder, 

Is there any other way to achieve this

**Comment by allebb** [comment]
At present there are a number of reasons why we don't do this at present
mainly due to the stability of Apache though (if in the event you delete
that 'web' folder then when Apache restarts it may fail to load because the
folder no longer exists and as this affects ALL users on the server we've
avoided doing this at present).

I would however recommend using a .htaccess file to direct traffic to the
'web' folder, I've used a similar .htaccess file to direct all traffic to
the 'public' folder in a Laravel application (which is the same as the
'web' folder in Symphony)

I'd just search online something like 'Symphony shared hosting .htaccess
file'... .although not ideal, should get you up and running :)

**Comment by vrdvaibhav** [comment]
OK , I will do it that way. 
I didn't thought about the stability issue for Apache. 
Zpanel is Great Work  :+1: 

Thank You

**Comment by allebb** [comment]
No problem, thanks and you are welcome :)
