### ISSUE TITLE
 Package Manager - Ram Quota

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#144]
Package Manager should have the ability for server admin and resellers add a ram quota to packages.

**Comment by ghost** [comment]
euh? How you want to handle a ram quota?

I don't think this could make to core and on windows. Provide how you plan this?

This is not an issue already and is more seen as a feature request.

Beware if you try to compare with Cpanel don't forget cpanel isolate each account with it's own user. Not the same case with zpanel.

**Comment by allebb** [comment]
Yeah kinda awkward to implement into the current way that ZPX is developed, eg. Apache is configured with mod_php as opposed to a 'partion-able', per-instance (eg. PHP-FPM implementation) and even if we was to switch that out, allocating 'RAM' on a per user basis would not be 'truely' possible anyways as I'm not aware of anyway in which to partition mail server and FTP memory allocation on a per user basis (I know this is anal but without the use of passthru VM's etc. this would be an extremely complex thing to achieve.)

Unless anyone has any bright ideas I'm going to close this FR atleast for ZPX (future versions of ZPanel would make this most possible due to *NIX user accounts and various other tricks ;))
