### ISSUE TITLE
MySQL User View

### ISSUE THREAD

**Issue by TheNigelist** [zpanel/zpanelx#158]
When packages set to unlimited (the default setting now), the MySql User Quota doesn't display properly.

I reported this issue at the old bugs site, but it was never fixed.
![mysql_user_quota_unlimited](https://f.cloud.github.com/assets/1205726/2444376/49034c04-ae52-11e3-9c88-53b4d400251c.png)

**Comment by g0ddish** [comment]
This guy was born with some extra chromosomes ignore this issue.

**Comment by stokes84** [comment]
Good catch Nigel easy fix too, wonder if there are anymore bugs that got lost in the sauce when the bugtracker got murdered. @g0ddish I'm good bro :stuck_out_tongue_winking_eye: lol

**Comment by TheNigelist** [comment]
Not sure. I've been looking for a while now. That was a bug from 10.0.2 > 10.1.0 upgrade.

**Comment by allebb** [comment]
I've fixed this and pushed here: https://github.com/zpanel/zpanelx/commit/3f98dcb0a48bfececfbff5b0da5ad4fb09d86035 not really sure why there was a quota chart anyway as ZPX has never limited the amount of  MySQL users accounts (a database can have multiple user accounts), I've therefore pushed a fix that implements a constant 'infinate' image and I have no intention of imposing limitations on the number of MySQL user accounts that a user should be able to create.

**Comment by ghost** [comment]
Users must be limited, as you can later limite number of connection per user and avoid users overloading DB as they can setup too many users. Very bad. Should be limited.

M B

**Comment by 5050** [comment]
@Me.B : unlimited is the easiest way for people whom handle a private server only for their own use, without any client.

**Comment by ghost** [comment]
@5050 So why having resellers? You can setup unllimited users even if you had the ability to set limits. We are talking here about how the feature is applied for shared hosting panel. Either you are the sole user or you are offering hosting. Your argument would apply for ftp accounts too. it's easier for one user to have unlimited indeed. BUT as long we can change that, for mysql zpanel dropped that. We should get it back.

We should extend more zpanel how we can control packages limits instead of reducing that.

this is discussed as #181
